### ISSUE TITLE
partly/grouped stacked bar chart

### ISSUE THREAD

**Issue by VincentVW** [d3plus/d3plus#571]
I have the same use case as Mr. Sandman here: 

http://stackoverflow.com/questions/40877196/partially-stacked-bar-chart-nvd3 (dont mind the nvd3 reference). 

So I have bar 1 that I want to compare with the combination of bar 2 and 3. 

I played around with d3plus a bit but seeing the structure it seems unlikely to me that this is something I can do out-of-the-box with d3plus.

So 2 short questions; did I miss anything and is this possible already? If not, @davelandry , since you know d3plus structure best, would it be feasible to create this? If so I'll give it a shot if I could get some directions and create a PR if more people would benefit from it.

**Comment by davelandry** [comment]
I think this should already be possible by manipulating the array passed to .id( ) for the groupings. Essentially, you'll group by each "column" of bars, and then the ones that should be stacked will be the only entry in that group.

Kind of weird to explain in text, but if you post a jsfiddle with some sample data you're trying to use I can help experiment with it.

**Comment by VincentVW** [comment]
Hi @davelandry , thanks for your response.

I've created this JsFiddle; https://jsfiddle.net/bt1xmb02/1/ and already fiddled around with it a bit to see if I could get it working, no success yet.

The example contains sample data for my use case, which is about yearly grouped incoming and outgoing funds in an aid project. Within this context we have the "incoming" group, with 1 bar "budgets". and the "outgoing" group, with 2 bars "Disbursed to other NGO" and "Spend". The goal is to stack the 2 bars in the outgoing group to make it easier to compare between incoming/outgoing.

Thanks for looking into this!

**Comment by davelandry** [comment]
@VincentVW looks like this isn't possible with the current build. I've modified this issue to be a feature request.

It may currently be possible with the new [d3plus-plot](https://github.com/d3plus/d3plus-plot) module, but it's not fully documented/tested yet. When this gets implemented, it will most likely get implemented in that repo.
