### ISSUE TITLE
treemap back button breaks the chart

### ISSUE THREAD

**Issue by andre-msantos** [d3plus/d3plus#701]
I'm trying to create a treemap chart and when the user click in some category, the chart shows drilldown of data. Drilldown is working fine, but when the user click in back button the chart not show parent category clicked.

When I try in jsfiddle was working, but in my website, with the same code, is not working, somebody could help me?

https://jsfiddle.net/andre_msantos/gkvwfe2n/7/ (it`s working fine)
https://cliquesus.com.br/radaronco/radar/pulmao/teste.html

When load:
![image](https://user-images.githubusercontent.com/12376581/87879756-094bf500-c9c3-11ea-8400-87ee4bdf2ae0.png)

When the user click to back:
![image](https://user-images.githubusercontent.com/12376581/87879771-21bc0f80-c9c3-11ea-8297-7d9d3c4afea3.png)

**Comment by drvillamizar** [comment]
Hi! I have the same problem! do you know how this can be avoided?
Thanks

**Comment by davelandry** [comment]
@andre-msantos or @drvillamizar: I can look into this, but the links posted here are all dead (I'm getting `404` errors). Can either of you reproduce the bug in a jsfiddle, or at least somewhere with a visible config?

**Comment by andre-msantos** [comment]
Sorry, Dave.

I created a new fiddle https://jsfiddle.net/andre_msantos/fj2vybdk/6/

Click in B series, resize window to show subgroup rectangles and after click in Back, the rectangle of B series does not appear again. The rectangle only appear if resize window.

**Comment by drvillamizar** [comment]
Thanks @andre-msantos. In my case I have solved it temporarily by asking the level on click event and if it is 0 I reload the data. It is not optimal but it serves me temporarily. 
For example: 
.on("click", function (d) {
                
                $(".d3plus-viz-back").click(function () {
                    var depth_aux = grafica.depth();
                     if (depth_aux == 1) {
                        ReloadDatosFunction(datos);
                    }
                });
            })

**Comment by drvillamizar** [comment]
HI! In mozilla it also happens when clicking not only the back button.

**Comment by davelandry** [comment]
thanks @andre-msantos and @drvillamizar! I can definitely confirm this is a bug, and we'll be looking into it. I'll keep you updated.

**Comment by davelandry** [comment]
@andre-msantos and @drvillamizar this has been fixed with the latest v2.0.1 release: https://jsfiddle.net/3mu68sho/
