### ISSUE TITLE
Module not found: Can't resolve './build/package'

### ISSUE THREAD

**Issue by dominickbrasileiro** [d3plus/d3plus#710]
Hello,

I'm using d3plus ^2.0.0 in a React JavaScript project and when I try to run it, this error appears:

```bash
Failed to compile.

./node_modules/d3plus/es/index.js
Module not found: Can't resolve './build/package' in '/path/to/project/node_modules/d3plus/es'
```

The file "package" doesn't exist inside ```node_modules/d3plus/es```. I removed the first line of the ```node_modules/d3plus/es/index.js``` file and everything worked, but the problem is that whenever I install any dependencies in the project, this file is overwritten and the error happens again.

Any solution? Thanks in advance.

**Comment by davelandry** [comment]
Hmm, that's interesting, definitely something we'll have to look into.

In the meantime, I would suggest installing and importing each individual d3plus module as you use them. It will cut down on your bundle size, as well as solve this issue.

So something like this: `import {Treemap} from "d3plus";`

Would become this: `import {Treemap} from "d3plus-hierarchy";`

https://github.com/d3plus/d3plus#modules

**Comment by antonkatz** [comment]
Same issue!

**Comment by SeanLMcCullough** [comment]
Part of the issue appears to be that "build/package.js" isn't listed in the "files" list of the package.json, so is excluded on publish.

Secondly, the build script doesn't appear to adjust relative paths, so the reference in index.js to `./build/package.js` should be  
compiled to `../build/package.js` as the index is moved to `es/index.js`, making the `package.js` unresolvable.

**Comment by davelandry** [comment]
@antonkatz @SeanLMcCullough I believe we have found a fix for this (we're now including the package file inside of the `es` directory). Can you two test to double-check me?
