### ISSUE TITLE
dom2canvas d3plus-export warning

### ISSUE THREAD

**Issue by danielamguerra** [d3plus/d3plus#725]
Warning received:

 WARN  in ./node_modules/d3plus/es/index.js                                                                                                                                                                       
"export 'dom2canvas' was not found in 'd3plus-export'

dom2canvas has been removed from d3plus-export version 1.3.0

Possible solution: Remove dom2canvas (line 45) from file d3plus/index.js

**Comment by davelandry** [comment]
@danielamguerra fixed with v2.1.1 of the `d3plus` package 🚀
